version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    command: --disable-partition-engine-check
    volumes:
      - ~/Documents/personal/docker-data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_USER=mattaltepeter
      - MYSQL_PASSWORD=alsosecret