version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      KAFKA_BROKER_ID: 1
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs-1
    volumes:
      - ~/Documents/personal/docker-data/kafka:/kafka
    depends_on:
      - zookeeper
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    ports:
      - "9000:9000"
    environment: 
      - ZK_HOSTS=zookeeper:2181
    volumes:
      - ~/Documents/personal/docker-data/kafka-manager:/srv/kafka-manager
    depends_on: 
      - zookeeper
      - kafka